SET FOREIGN_KEY_CHECKS = 0;

DROP TABLE IF EXISTS f_recents;
DROP TABLE IF EXISTS f_favorites;
DROP TABLE IF EXISTS f_ratings;
DROP TABLE IF EXISTS f_watches;
DROP TABLE IF EXISTS f_servers;
DROP TABLE IF EXISTS f_customers;
DROP TABLE IF EXISTS f_media;
DROP TABLE IF EXISTS f_movies;

CREATE TABLE f_movies(M_ID INT NOT NULL AUTO_INCREMENT,
  title varchar(200) NOT NULL,
  genre varchar(50) NOT NULL,
  runtime_minutes VARCHAR(4) NOT NULL,
  release_date DATE NOT NULL,
  acquire_date DATE NOT NULL,
  avg_rating DECIMAL(3,2),
  mpaa_rating varchar(5) NOT NULL,
  PRIMARY KEY(M_ID)
  ) ENGINE=INNODB;

#NOTE: media is filename pointer to actual location on server
CREATE TABLE f_media (
  MEDIA_ID int NOT NULL AUTO_INCREMENT,
  M_ID int NOT NULL,
  filename VARCHAR(255) NOT NULL,
  mimetype varchar(255) DEFAULT 'jpg',
  PRIMARY KEY(MEDIA_ID),
  FOREIGN KEY(M_ID) REFERENCES f_movies(M_ID) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=INNODB  DEFAULT CHARSET=utf8;

CREATE TABLE f_customers(C_ID INT NOT NULL AUTO_INCREMENT,
  S_ID INT,
  name varchar(100) NOT NULL,
  email varchar(100) NOT NULL,
  subscribe_begin DATETIME NOT NULL,
  subscribe_end DATETIME NOT NULL,
  PRIMARY KEY(C_ID)
  ) ENGINE=INNODB;
# NOTE: add FOREIGN KEY(S_ID) REFERENCES F_SERVERS(S_ID) later!

CREATE TABLE f_servers(S_ID INT NOT NULL AUTO_INCREMENT,
  location varchar(50) NOT NULL,
  PRIMARY KEY(S_ID)
  ) ENGINE=INNODB;

CREATE TABLE f_watches(C_ID INT NOT NULL,
  M_ID INT NOT NULL,
  rating TINYINT,
  PRIMARY KEY(C_ID, M_ID),
  FOREIGN KEY(C_ID) REFERENCES f_customers(C_ID) ON DELETE CASCADE ON UPDATE CASCADE,
  FOREIGN KEY(M_ID) REFERENCES f_movies(M_ID) ON DELETE CASCADE ON UPDATE CASCADE
  ) ENGINE=INNODB;

CREATE TABLE f_ratings(C_ID INT NOT NULL,
  M_ID INT NOT NULL,
  rating TINYINT NOT NULL,
  PRIMARY KEY(C_ID, M_ID),
  FOREIGN KEY(C_ID) REFERENCES f_customers(C_ID) ON DELETE CASCADE ON UPDATE CASCADE,
  FOREIGN KEY(M_ID) REFERENCES f_movies(M_ID) ON DELETE CASCADE ON UPDATE CASCADE
  ) ENGINE=INNODB;

CREATE TABLE f_favorites(C_ID INT NOT NULL,
  M_ID INT NOT NULL,
  PRIMARY KEY(C_ID, M_ID),
  FOREIGN KEY(C_ID) REFERENCES f_customers(C_ID) ON DELETE CASCADE ON UPDATE CASCADE,
  FOREIGN KEY(M_ID) REFERENCES f_movies(M_ID) ON DELETE CASCADE ON UPDATE CASCADE
  ) ENGINE=INNODB;

CREATE TABLE f_recents(C_ID INT NOT NULL,
  M_ID INT NOT NULL,
  PRIMARY KEY(C_ID, M_ID),
  FOREIGN KEY(C_ID) REFERENCES f_customers(C_ID) ON DELETE CASCADE ON UPDATE CASCADE,
  FOREIGN KEY(M_ID) REFERENCES f_movies(M_ID) ON DELETE CASCADE ON UPDATE CASCADE
  ) ENGINE=INNODB;

# Add FK constraint to F_CUSTOMERS: FOREIGN KEY(S_ID) REFERENCES F_SERVERS(S_ID)
ALTER TABLE f_customers MODIFY COLUMN S_ID INT NOT NULL,
    ADD CONSTRAINT fk_f_customers_S_ID
    FOREIGN KEY (S_ID)
    REFERENCES f_servers(S_ID) ON DELETE CASCADE ON UPDATE CASCADE;

SET FOREIGN_KEY_CHECKS = 1;